@endpoint = http://localhost:3000/api/v1/cars

###

# @name postACar
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 2020
}

###

# Missing make
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "model": "Corolla",
  "year": 2020
}

###

# Empty make
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "make": "",
  "model": "Corolla",
  "year": 2020
}

###

# Invalid year
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 1949
}

###

# Wrong type for year
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "make": "Toyota",
  "model": "Corolla",
  "year": "2020"
}

###

@newCar = {{postACar.response.body._id}}

###

GET {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

###

GET {{endpoint}} HTTP/1.1
content-type: application/json

###

GET {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

###

# Valid update - all fields
PUT {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "make": "Toyota",
  "model": "Camry",
  "year": 2022
}

###

# Valid update - make only
PUT {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "make": "Honda"
}

###

# Valid update - year only
PUT {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "year": 2023
}

###

# Invalid update - empty make
PUT {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "make": "",
  "model": "Civic",
  "year": 2023
}

###

# Invalid update - year below 1950
PUT {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "make": "Honda",
  "model": "Civic",
  "year": 1949
}

###

# Invalid update - year is a string
PUT {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "make": "Honda",
  "model": "Civic",
  "year": "2023"
}

###

DELETE {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah