@endpoint = http://localhost:3000/api/v1/cars

###

# @name postACar
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 2020
}

###

# Missing make
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "model": "Corolla",
  "year": 2020
}

###

# Empty make
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "make": "",
  "model": "Corolla",
  "year": 2020
}

###

# Invalid year
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 1949
}

###

# Wrong type for year
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
  "make": "Toyota",
  "model": "Corolla",
  "year": "2020"
}

###

@newCar = {{postACar.response.body._id}}

###

GET {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

###

GET {{endpoint}} HTTP/1.1
content-type: application/json

###

GET {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

###

PUT {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
    "make": "Toyota",
    "model": "Yaris"
}

###

DELETE {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah