@endpoint = http://localhost:3000/api/v1/cars

###

# @name PostACar
POST {{endpoint}} HTTP/1.1
Content-Type: application/json

{
    "make": "Toyota",
    "model": "Corolla"
}

###

@newCar = {{PostACar.response.body._id}}

###
GET  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json

###

GET {{endpoint}} HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/api/v1/cars HTTP/1.1
content-type: application/json
x-api-key: blahblah


###

GET {{endpoint}}/{{PostACar.response.body.$._id}} HTTP/1.1
Content-Type: application/json

###

PUT {{endpoint}}/{{PostACar.response.body.$._id}} HTTP/1.1
Content-Type: application/json

{
    "make": "Toyota",
    "model": "Yaris"
}

###

DELETE {{endpoint}}/{{PostACar.response.body.$._id}} HTTP/1.1
Content-Type: application/json